server:
  port: 8083

spring:
  application:
    name: billing-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0   # 100% de las peticiones se trazan
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
